### ISSUE TITLE
axe-webdriverjs deprecated 

### ISSUE THREAD

**Issue by mgifford** [elenatorro/axe-report-generator#1]
Just noting this issue. Not sure if there is a more actively maintained tool for this. 

axe-webdriverjs deprecated Error must be handled as the first argument of axe.analyze. See: #83 index.js:24:14

**Comment by elenatorro** [comment]
Hi @mgifford, thanks! I'll take a look 👀

**Comment by mgifford** [comment]
Thanks @elenatorro - might be tied to this https://github.com/dequelabs/axe-webdriverjs/issues/146

In case it helps:

```
axe-report-generator$ npm run generate

> axe-report-generator@0.0.1 generate /Users/mikegifford/axe-report-generator
> node index

axe-webdriverjs deprecated Error must be handled as the first argument of axe.analyze. See: #83 index.js:24:14
(node:40182) UnhandledPromiseRejectionWarning: TimeoutError: Waiting for title to be "Elena Torro"
Wait timed out after 1097ms
    at /Users/mikegifford/axe-report-generator/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:40182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:40182) UnhandledPromiseRejectionWarning: NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
    at promise.finally (/Users/mikegifford/axe-report-generator/node_modules/selenium-webdriver/lib/webdriver.js:730:38)
    at Object.thenFinally [as finally] (/Users/mikegifford/axe-report-generator/node_modules/selenium-webdriver/lib/promise.js:124:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:40182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:40182) UnhandledPromiseRejectionWarning: Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:62528
    at ClientRequest.<anonymous> (/Users/mikegifford/axe-report-generator/node_modules/selenium-webdriver/http/index.js:262:15)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:40182) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```
